language: python
python: 
  - "3.6"
branches:
  only:
    - master
    - develop
    - wasm-tests
sudo: false
install: "pip install pyyaml jsonschema pysha3"
script:

# sanitation checks against testsets
- make sani
